use_frameworks!

target 'OtiNetwork_Example' do
  pod 'OtiNetwork', :path => '../'

  target 'OtiNetwork_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
