//
//  ServiceEndPoint.swift
//  BaseProject
//
//  Created by Cüneyt AYVAZ on 2.07.2019.
//  Copyright © 2019 OtiHolding. All rights reserved.
//

import Foundation

public enum ServiceEndPoint: String {
    case CreateToken = "/api/api/User/GetToken"
    case GetUser = "/api/api/User/GetMyInfo"
    case GetGuideMarkets = "/api/api/IndShop/GetGuideMarkets"
    case GetHotelsMobie = "/api/api/TourSale/GetHotelsMobile"
    case GetInHouseList = "/api/api/IndShop/GetInHouseList"
    case GetTouristInfo = "/api/api/IndShop/GetTouristInfo"
    case GetSelectList = "/api/api/Company/GetSelectList"
    case GetSaveForMobile = "/api/api/IndShop/SaveForMobile"
    case GetGuideInfo =  "/api/api/IndShop/GetGuideInfo"
    case GetGuideAnnoucemenstAndDocuments = "/api//api/Announcement/GetGuideAnnouncementsAndDocuments"
    case TourGetSelectList = "/api/api/TourDefinition/GetSelectList"
    case TourGetTourDetailForMobile = "/api/api/TourSale/GetTourDetailForMobile"
    case GetIndShopDetailForMobile = "/api/api/IndShop/GetIndShopDetailForMobile2"
    case GetVoucherDetail = "/api/api/TourSale/GetVoucherDetail"
    case GetMobilCancelRules = "/api/api/TourSaleCancel/GetMobileCancelRules"
    case GetPaymentTypes = "/api/api/TourSale/GetPaymentTypes"
    case GetCalculateCancelFee = "/api/api/TourSaleCancel/CalculateCancelFee"
    case GetTourSaleCancelMobile = "/api/api/TourSaleCancel/CancelMobile"
    case GetHotelSelectListByAreaRef = "/api/api/Hotel/GetHotelSelectListByAreaRef"
    case GetGuideSelectList = "/api/api/Guide/GetSelectList"
    case GetSpeakTimeForMobile = "/api/api/GSpeakTime/GetSpeakTimeForMobile"
    case GetSearchZReport = "/api/api/AccountingZReportMobile/SearchZReport"
    case GetZReportData = "/api/api/AccountingZReportMobile/GetReportData"
    case GetZReportPayments = "/api/api/AccountingZReportMobile/GetReportPayments"
    case GetZReportRefunds = "/api/api/AccountingZReportMobile/GetReportRefunds"
    case GetGuideDailyReport = "/api/api/AccountingZReportMobile/GetGuideDailyReport"
    case GetZReportPreview = "/api/api/AccountingZReportMobile/GetReportPreview"
    case GetCreateZReportPreview = "/api/api/AccountingZReportMobile/CreateZReport"
    case GetTourSaleSearchTour = "/api/api/TourSale/SearchTour"
    case GetTourSearchCache = "/api/api/TourSale/GetTourSearchCache"
    case GetCurrencySelectList = "/api/api/Currency/GetSelectList"
    case GetExhangeRates = "/api/api/Exchange/GetExhangeRates"
    case GetMaxGuideVoucherNumber = "/api/api/TourSale/GetMaxGuideVoucherNumber"
    case GetSaveMobileSale = "/api/api/TourSale/SaveMobileSale"
    case GetTourSalePromotions = "/api/api/TourSale/GetPromotions"
    case GetApplyPromotionMobile = "/api/api/TourSale/ApplyPromotionMobile"
    case GetInHouseListForMobile = "/api/api/TourSale/GetInHouseListForMobile"
    case GetGuideDuties = "/api/api/TourTransferPlan/GetGuideDuties"
    case GetArrAndDepHotelListForMobile = "/api/api/TourTransferPlan/GetArrAndDepHotelListForMobile"
    case GetHotelListForMobile = "/api/api/TourTransferPlan/GetHotelListForMobile"
    case GetInter = "/api/api/TourTransferPlan/GetInter"
    case GetIndShopHotelListForMobile = "/api/api/IndShop/GetIndShopHotelListForMobile"
    case GetInterPaxes = "/api/api/TourTransferPlan/GetInterPaxes"
    case GetInfoPaxes = "/api/api/TourTransferPlan/GetInfoPaxes"
    case GetArrAndDepPaxes = "/api/api/TourTransferPlan/GetArrAndDepPaxes"
    case GetTourPaxes = "/api/api/TourTransferPlan/GetTourPaxes"
    case GetColAndDelPaxes = "/api/api/TourTransferPlan/GetColAndDelPaxes"
    case GetIndShopPaxes = "/api/api/IndShop/GetIndShopPaxes"
    case UpdateIndShopNoShow = "/api/api/IndShop/UpdateIndShopNoShow"
    case UpdateNoShow = "/api/api/TourTransferPlan/UpdateNoShow"
    case UpdateInfoPlanNoShow = "/api/api/TourTransferPlan/UpdateInfoPlanNoShow"
    case UpdateArrAndDepPlanNoShow = "/api/api/TourTransferPlan/UpdateArrAndDepPlanNoShow"
    case SaveGuideMeetingTimeAndReport = "/api/api/TourTransferPlan/SaveGuideMeetingTimeAndReport?userId=1&langId=1&"
    case SendSaveGuideMeetingTimeAndReport = "/api/api/TourTransferPlan/SaveGuideMeetingTimeAndRepot"
    case GetUpdateSaleNoteforMobile = "/api/api/TourSale/UpdateSaleNoteforMobile"
    case GetTourEventDetail = "/api/api/TourTransferPlan/GetTourEventDetail"
    case GetSteps = "/api/api/ServiceVoucherNew/GetSteps"
    case GetSteps_ArrDepH2H = "/api/api/ServiceVoucherNew/GetSteps_ArrDepH2H"
    case GetStepsForIndShop = "/api/api/ServiceVoucherNew/GetStepsForIndShop"
    case GetStepDetail = "/api/api/ServiceVoucherNew/GetStepDetail"
    case GetStepDetail_ShopSupplier = "/api/api/ServiceVoucherNew/GetStepDetail_ShopSupplier"
    case GetStepDetail_IndShopSupplier = "/api/api/ServiceVoucherNew/GetStepDetail_IndShopSupplier"
    case GetStepDetail_ArrDepH2H = "/api/api/ServiceVoucherNew/GetStepDetail_ArrDepH2H"
    case GetStepDetail_ArrDepH2H_ShopSupplier = "/api/api/ServiceVoucherNew/GetStepDetail_ArrDepH2H_ShopSupplier"
    case IsCompanyUserValid = "/api/api/ServiceVoucherNew/IsCompanyUserValid"
    case IsCompanyUserValid_ArrDepH2H = "/api/api/ServiceVoucherNew/IsCompanyUserValid_ArrDepH2H"
    case IndShopIsCompanyUserValid = "/api/api/ServiceVoucher/IndShopIsCompanyUserValid"
    case CreateServiceVoucher = "/api/api/ServiceVoucherNew/CreateServiceVoucher"
    case CreateServiceVoucher_ShopSupplier = "/api/api/ServiceVoucherNew/CreateServiceVoucher_ShopSupplier"
    case CreateServiceVoucher_IndShopSupplier = "/api/api/ServiceVoucherNew/CreateServiceVoucher_IndShopSupplier"
    case CreateServiceVoucher_ArrDepH2H = "/api/api/ServiceVoucherNew/CreateServiceVoucher_ArrDepH2H"
    case CreateServiceVoucher_ArrDepH2H_ShopSupplier = "/api/api/ServiceVoucherNew/CreateServiceVoucher_ArrDepH2H_ShopSupplier"
    case GetCompanyUsers = "/api/api/ServiceVoucherNew/GetCompanyUsers"
    case GetCompanyUsers_ArrDepH2H = "/api/api/ServiceVoucherNew/GetCompanyUsers_ArrDepH2H"
    case GetVoucherForGoShow = "/api/api/TourTransferPlan/GetVoucherForGoShow"
    case SetGoShowOnMobile = "/api/api/TourTransferPlan/SetGoShowOnMobile"
    case GetBirthDays = "/api/api/TourTransferPlan/GetBirthDays"
}
